export type DashboardMetricCategory =
  | 'finance'
  | 'sales'
  | 'marketing'
  | 'products'
  | 'customers'
  | 'operations'
  | 'ai_insights';

export type DashboardDisplayType = 'card' | 'chart' | 'table' | 'list';

export type DashboardMetricDefinition = {
  key: string;
  label: string;
  description: string;
  category: DashboardMetricCategory;
  requiredData: string[];
  supportedBusinessTypes: string[];
  defaultEnabled: boolean;
  planAvailability: string[];
  displayType: DashboardDisplayType;
};

export const CORE_DASHBOARD_METRIC_KEYS = [
  'revenue',
  'losses',
  'profit',
  'cash_flow',
  'company_count',
  'ai_roi',
  'alerts_insights',
];

export const CORE_DASHBOARD_METRIC_SET = new Set(CORE_DASHBOARD_METRIC_KEYS);

export const DASHBOARD_METRICS: DashboardMetricDefinition[] = [
  {
    key: 'revenue',
    label: 'Receita',
    description: 'Total vendido no periodo selecionado.',
    category: 'finance',
    requiredData: ['sales', 'financial_transactions'],
    supportedBusinessTypes: ['ecommerce', 'saas', 'services', 'medical', 'law', 'retail', 'infoproduct'],
    defaultEnabled: true,
    planAvailability: ['COMUM', 'PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'profit',
    label: 'Lucro',
    description: 'Receita menos saidas, custos operacionais e midia paga.',
    category: 'finance',
    requiredData: ['sales', 'financial_transactions', 'ad_spend'],
    supportedBusinessTypes: ['ecommerce', 'saas', 'services', 'medical', 'law', 'retail', 'infoproduct'],
    defaultEnabled: true,
    planAvailability: ['COMUM', 'PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'losses',
    label: 'Perdas',
    description: 'Saidas, despesas e custos do periodo.',
    category: 'finance',
    requiredData: ['financial_transactions', 'ad_spend'],
    supportedBusinessTypes: ['ecommerce', 'saas', 'services', 'medical', 'law', 'retail', 'infoproduct'],
    defaultEnabled: true,
    planAvailability: ['COMUM', 'PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'net_profit',
    label: 'Lucro liquido',
    description: 'Resultado liquido estimado apos custos e despesas.',
    category: 'finance',
    requiredData: ['sales', 'operational_costs', 'products'],
    supportedBusinessTypes: ['ecommerce', 'saas', 'services', 'retail', 'infoproduct'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'cash_flow',
    label: 'Fluxo de caixa',
    description: 'Resumo de entradas e saidas no periodo.',
    category: 'finance',
    requiredData: ['financial_transactions'],
    supportedBusinessTypes: ['ecommerce', 'saas', 'services', 'medical', 'law', 'retail', 'infoproduct'],
    defaultEnabled: true,
    planAvailability: ['COMUM', 'PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'cash_flow_summary',
    label: 'Resumo de caixa',
    description: 'Grafico de fluxo financeiro por faixa de tempo.',
    category: 'finance',
    requiredData: ['sales', 'financial_transactions'],
    supportedBusinessTypes: ['ecommerce', 'saas', 'services', 'medical', 'law', 'retail', 'infoproduct'],
    defaultEnabled: false,
    planAvailability: ['COMUM', 'PRO', 'ENTERPRISE'],
    displayType: 'chart',
  },
  {
    key: 'category_mix',
    label: 'Mix do periodo',
    description: 'Distribuicao das principais fontes de receita.',
    category: 'sales',
    requiredData: ['sales', 'financial_transactions'],
    supportedBusinessTypes: ['ecommerce', 'saas', 'services', 'medical', 'law', 'retail', 'infoproduct'],
    defaultEnabled: false,
    planAvailability: ['COMUM', 'PRO', 'ENTERPRISE'],
    displayType: 'chart',
  },
  {
    key: 'sales_count',
    label: 'Quantidade de vendas',
    description: 'Numero de vendas registradas no periodo.',
    category: 'sales',
    requiredData: ['sales'],
    supportedBusinessTypes: ['ecommerce', 'saas', 'services', 'medical', 'law', 'retail', 'infoproduct'],
    defaultEnabled: false,
    planAvailability: ['COMUM', 'PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'company_count',
    label: 'Empresas vinculadas',
    description: 'Quantidade de empresas disponiveis para o usuario.',
    category: 'operations',
    requiredData: ['companies'],
    supportedBusinessTypes: ['ecommerce', 'saas', 'services', 'medical', 'law', 'retail', 'infoproduct'],
    defaultEnabled: true,
    planAvailability: ['COMUM', 'PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'average_ticket',
    label: 'Ticket medio',
    description: 'Valor medio por venda no periodo.',
    category: 'sales',
    requiredData: ['sales'],
    supportedBusinessTypes: ['ecommerce', 'saas', 'services', 'medical', 'law', 'retail', 'infoproduct'],
    defaultEnabled: false,
    planAvailability: ['COMUM', 'PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'peak_sales_hours',
    label: 'Horarios de pico',
    description: 'Faixas de horario com maior volume de vendas.',
    category: 'sales',
    requiredData: ['sales'],
    supportedBusinessTypes: ['ecommerce', 'retail', 'services', 'medical', 'law'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'chart',
  },
  {
    key: 'conversion_rate',
    label: 'Taxa de conversao',
    description: 'Percentual de leads ou visitantes que viram venda.',
    category: 'marketing',
    requiredData: ['leads', 'sales'],
    supportedBusinessTypes: ['ecommerce', 'saas', 'services', 'infoproduct'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'cac',
    label: 'CAC',
    description: 'Custo medio para adquirir um cliente.',
    category: 'marketing',
    requiredData: ['ad_spend', 'customers'],
    supportedBusinessTypes: ['ecommerce', 'saas', 'services', 'infoproduct'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'roi',
    label: 'ROI',
    description: 'Retorno sobre investimento estimado no periodo.',
    category: 'marketing',
    requiredData: ['sales', 'ad_spend', 'operational_costs'],
    supportedBusinessTypes: ['ecommerce', 'saas', 'services', 'retail', 'infoproduct'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'roas',
    label: 'ROAS',
    description: 'Retorno sobre investimento em anuncios.',
    category: 'marketing',
    requiredData: ['ad_spend', 'sales'],
    supportedBusinessTypes: ['ecommerce', 'retail', 'infoproduct', 'services'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'margin',
    label: 'Margem',
    description: 'Margem estimada cruzando vendas, produtos e custos.',
    category: 'products',
    requiredData: ['sales', 'products', 'operational_costs'],
    supportedBusinessTypes: ['ecommerce', 'retail', 'services', 'infoproduct'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'profit_by_product',
    label: 'Lucro por produto',
    description: 'Ranking de produtos por lucro estimado.',
    category: 'products',
    requiredData: ['sales', 'products'],
    supportedBusinessTypes: ['ecommerce', 'retail', 'infoproduct'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'table',
  },
  {
    key: 'best_selling_products',
    label: 'Produtos mais vendidos',
    description: 'Produtos com maior receita registrada.',
    category: 'products',
    requiredData: ['sales'],
    supportedBusinessTypes: ['ecommerce', 'retail', 'infoproduct'],
    defaultEnabled: false,
    planAvailability: ['COMUM', 'PRO', 'ENTERPRISE'],
    displayType: 'list',
  },
  {
    key: 'customers_acquired',
    label: 'Clientes adquiridos',
    description: 'Novos clientes cadastrados no periodo.',
    category: 'customers',
    requiredData: ['customers'],
    supportedBusinessTypes: ['ecommerce', 'saas', 'services', 'medical', 'law', 'retail', 'infoproduct'],
    defaultEnabled: false,
    planAvailability: ['COMUM', 'PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'repeat_customers',
    label: 'Clientes recorrentes',
    description: 'Clientes que voltaram a comprar ou conversar.',
    category: 'customers',
    requiredData: ['customers', 'sales', 'conversations'],
    supportedBusinessTypes: ['ecommerce', 'saas', 'services', 'medical', 'law', 'retail'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'ltv',
    label: 'LTV',
    description: 'Valor medio estimado do cliente ao longo do relacionamento.',
    category: 'customers',
    requiredData: ['customers', 'sales'],
    supportedBusinessTypes: ['ecommerce', 'saas', 'services', 'medical', 'law', 'retail', 'infoproduct'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'operational_costs',
    label: 'Custos operacionais',
    description: 'Total de custos operacionais cadastrados.',
    category: 'operations',
    requiredData: ['operational_costs'],
    supportedBusinessTypes: ['ecommerce', 'saas', 'services', 'medical', 'law', 'retail', 'infoproduct'],
    defaultEnabled: false,
    planAvailability: ['COMUM', 'PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'waste_inefficiency',
    label: 'Desperdicio operacional',
    description: 'Percentual de custo operacional sobre receita.',
    category: 'operations',
    requiredData: ['sales', 'operational_costs'],
    supportedBusinessTypes: ['ecommerce', 'services', 'retail'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'alerts_insights',
    label: 'Alertas e insights',
    description: 'Diagnosticos automaticos da IA para o periodo.',
    category: 'ai_insights',
    requiredData: ['sales', 'financial_transactions', 'operational_costs'],
    supportedBusinessTypes: ['ecommerce', 'saas', 'services', 'medical', 'law', 'retail', 'infoproduct'],
    defaultEnabled: true,
    planAvailability: ['COMUM', 'PRO', 'ENTERPRISE'],
    displayType: 'list',
  },
  {
    key: 'ai_roi',
    label: 'ROI da IA',
    description: 'Vendas e receita atribuidas ao atendente de IA.',
    category: 'ai_insights',
    requiredData: ['conversations', 'sales'],
    supportedBusinessTypes: ['ecommerce', 'saas', 'services', 'medical', 'law', 'retail', 'infoproduct'],
    defaultEnabled: true,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'revenue_forecast',
    label: 'Projecao simples de receita',
    description: 'Projecao por media movel baseada em historico real de vendas.',
    category: 'ai_insights',
    requiredData: ['sales'],
    supportedBusinessTypes: ['ecommerce', 'saas', 'services', 'retail', 'infoproduct'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'chart',
  },
  {
    key: 'market_opportunities',
    label: 'Oportunidades de mercado',
    description: 'Sinais de mercado e oportunidades sugeridas pela IA.',
    category: 'ai_insights',
    requiredData: ['products', 'market_prices', 'market_trends'],
    supportedBusinessTypes: ['ecommerce', 'retail', 'infoproduct'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'list',
  },
  {
    key: 'refund_rate',
    label: 'Taxa de reembolso',
    description: 'Percentual de vendas devolvidas ou reembolsadas.',
    category: 'sales',
    requiredData: ['refunds', 'sales'],
    supportedBusinessTypes: ['ecommerce_digital', 'infoproduct'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'funnel_conversion',
    label: 'Conversao do funil',
    description: 'Conversao entre etapas do funil comercial.',
    category: 'marketing',
    requiredData: ['funnel_events'],
    supportedBusinessTypes: ['ecommerce_digital', 'saas', 'services'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'mrr',
    label: 'MRR',
    description: 'Receita recorrente mensal.',
    category: 'finance',
    requiredData: ['subscriptions'],
    supportedBusinessTypes: ['saas'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'churn',
    label: 'Churn',
    description: 'Cancelamentos e perda de receita recorrente.',
    category: 'customers',
    requiredData: ['subscriptions'],
    supportedBusinessTypes: ['saas'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'activation_rate',
    label: 'Ativacao',
    description: 'Clientes que chegaram ao primeiro valor dentro do produto.',
    category: 'customers',
    requiredData: ['product_events'],
    supportedBusinessTypes: ['saas'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'retention',
    label: 'Retencao',
    description: 'Retencao de clientes em janelas recorrentes.',
    category: 'customers',
    requiredData: ['subscriptions', 'customer_activity'],
    supportedBusinessTypes: ['saas'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'active_customers',
    label: 'Clientes ativos',
    description: 'Clientes ativos no periodo.',
    category: 'customers',
    requiredData: ['customer_activity'],
    supportedBusinessTypes: ['saas'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'plan_conversion',
    label: 'Conversao de plano',
    description: 'Conversao de teste ou lead para plano pago.',
    category: 'marketing',
    requiredData: ['subscriptions', 'trials'],
    supportedBusinessTypes: ['saas'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'client_revenue',
    label: 'Receita por cliente',
    description: 'Receita atribuida por cliente ou contrato.',
    category: 'customers',
    requiredData: ['customers', 'sales'],
    supportedBusinessTypes: ['agency', 'services'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'profit_margin',
    label: 'Margem de lucro',
    description: 'Margem de lucro operacional.',
    category: 'finance',
    requiredData: ['sales', 'operational_costs'],
    supportedBusinessTypes: ['agency', 'services'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'customer_retention',
    label: 'Retencao de clientes',
    description: 'Clientes que permanecem comprando ou renovando.',
    category: 'customers',
    requiredData: ['customers', 'sales'],
    supportedBusinessTypes: ['agency', 'services'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'lead_conversion',
    label: 'Conversao de leads',
    description: 'Leads que viram cliente, consulta ou venda.',
    category: 'marketing',
    requiredData: ['leads', 'sales'],
    supportedBusinessTypes: ['agency', 'law_office', 'services'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'appointments',
    label: 'Consultas',
    description: 'Consultas ou agendamentos realizados.',
    category: 'sales',
    requiredData: ['appointments'],
    supportedBusinessTypes: ['medical_clinic'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'no_show_rate',
    label: 'No-show',
    description: 'Percentual de faltas em consultas/agendamentos.',
    category: 'operations',
    requiredData: ['appointments'],
    supportedBusinessTypes: ['medical_clinic'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'service_revenue',
    label: 'Receita de servicos',
    description: 'Receita ligada a servicos, consultas ou contratos.',
    category: 'finance',
    requiredData: ['sales'],
    supportedBusinessTypes: ['medical_clinic', 'law_office', 'local_services', 'services'],
    defaultEnabled: false,
    planAvailability: ['COMUM', 'PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'new_patients',
    label: 'Novos pacientes',
    description: 'Pacientes cadastrados no periodo.',
    category: 'customers',
    requiredData: ['customers'],
    supportedBusinessTypes: ['medical_clinic'],
    defaultEnabled: false,
    planAvailability: ['COMUM', 'PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'returning_patients',
    label: 'Pacientes recorrentes',
    description: 'Pacientes que retornaram no periodo.',
    category: 'customers',
    requiredData: ['appointments', 'customers'],
    supportedBusinessTypes: ['medical_clinic'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'leads',
    label: 'Leads',
    description: 'Leads recebidos no periodo.',
    category: 'marketing',
    requiredData: ['leads'],
    supportedBusinessTypes: ['law_office', 'agency', 'services'],
    defaultEnabled: false,
    planAvailability: ['COMUM', 'PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'consultations',
    label: 'Consultas iniciais',
    description: 'Consultas ou reunioes comerciais qualificadas.',
    category: 'sales',
    requiredData: ['appointments', 'leads'],
    supportedBusinessTypes: ['law_office', 'services'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'case_pipeline',
    label: 'Pipeline de casos',
    description: 'Oportunidades ou casos em andamento.',
    category: 'operations',
    requiredData: ['pipeline'],
    supportedBusinessTypes: ['law_office'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'list',
  },
  {
    key: 'client_followup',
    label: 'Follow-up de clientes',
    description: 'Clientes aguardando retorno ou proxima acao.',
    category: 'customers',
    requiredData: ['tasks', 'conversations'],
    supportedBusinessTypes: ['law_office', 'services'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'list',
  },
  {
    key: 'bookings',
    label: 'Agendamentos',
    description: 'Servicos agendados no periodo.',
    category: 'sales',
    requiredData: ['appointments'],
    supportedBusinessTypes: ['local_services', 'restaurant'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'stock_movement',
    label: 'Movimento de estoque',
    description: 'Entradas e saidas de estoque.',
    category: 'products',
    requiredData: ['inventory'],
    supportedBusinessTypes: ['retail_store', 'ecommerce_physical'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'peak_hours',
    label: 'Horarios de pico',
    description: 'Horarios mais fortes de venda ou pedido.',
    category: 'sales',
    requiredData: ['sales'],
    supportedBusinessTypes: ['restaurant', 'retail_store'],
    defaultEnabled: false,
    planAvailability: ['COMUM', 'PRO', 'ENTERPRISE'],
    displayType: 'chart',
  },
  {
    key: 'best_selling_items',
    label: 'Itens mais vendidos',
    description: 'Itens ou pratos com maior volume de venda.',
    category: 'products',
    requiredData: ['sales'],
    supportedBusinessTypes: ['restaurant'],
    defaultEnabled: false,
    planAvailability: ['COMUM', 'PRO', 'ENTERPRISE'],
    displayType: 'list',
  },
  {
    key: 'delivery_costs',
    label: 'Custos de delivery',
    description: 'Custos ligados a entrega e operacao de delivery.',
    category: 'operations',
    requiredData: ['operational_costs'],
    supportedBusinessTypes: ['restaurant'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'marketplace_fees',
    label: 'Taxas de marketplace',
    description: 'Taxas e comissoes cobradas pelo marketplace.',
    category: 'operations',
    requiredData: ['marketplace_orders', 'operational_costs'],
    supportedBusinessTypes: ['marketplace_seller'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
  {
    key: 'shipping_costs',
    label: 'Custos de frete',
    description: 'Custos de frete ou envio por venda.',
    category: 'operations',
    requiredData: ['shipping_costs', 'orders'],
    supportedBusinessTypes: ['marketplace_seller', 'ecommerce_physical'],
    defaultEnabled: false,
    planAvailability: ['PRO', 'ENTERPRISE'],
    displayType: 'card',
  },
];

export const DASHBOARD_METRIC_KEYS = new Set(DASHBOARD_METRICS.map((metric) => metric.key));

export function getMetricDefinition(metricKey: string) {
  return DASHBOARD_METRICS.find((metric) => metric.key === metricKey) || null;
}
