ALTER TABLE "User" DROP CONSTRAINT IF EXISTS "User_companyId_fkey";

ALTER TABLE "User"
ADD CONSTRAINT "User_companyId_fkey"
FOREIGN KEY ("companyId") REFERENCES "Company"("id")
ON DELETE SET NULL
ON UPDATE CASCADE;
